language: node_js

node_js:
 - "0.10"
 - "0.8"

before_install:
 - sudo apt-add-repository --yes ppa:chris-lea/node.js
 - sudo apt-add-repository --yes ppa:mapnik/boost
 - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get -y update -qq
 - sudo apt-get -y install git gcc-4.7 g++-4.7 build-essential nodejs libboost-dev zlib1g-dev protobuf-compiler libprotobuf-lite7 libprotobuf-dev libexpat1-dev libsparsehash-dev
 - git clone https://github.com/scrosby/OSM-binary.git
 - cd OSM-binary/src
 - make && sudo make install
 - cd ../../

install:
 - npm install mocha

before_script:
 - git clone https://github.com/osmcode/libosmium.git ../libosmium
 - CXX=g++-4.7 npm install --verbose

script:
 - make test
